# Generated by Django 2.0.2 on 2018-03-01 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=255, verbose_name='saved address name')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 2')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, verbose_name='country')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
                ('postal_code', models.CharField(max_length=255, verbose_name='postal code')),
                ('phone_number', models.CharField(max_length=255, verbose_name='phone_number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.BooleanField(default=False)),
                ('left_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='left by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_all_feedback', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other/Prefer Not to say')], default=2, verbose_name='gender')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', verbose_name='timezone')),
                ('public_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='public name')),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='public email')),
                ('public_url', models.URLField(blank=True, null=True, verbose_name='public URL')),
                ('merchant_id', models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='merchant id')),
                ('date_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='date format')),
                ('time_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='time format')),
                ('use_gravatar', models.BooleanField(default=False, verbose_name='use gravatar')),
                ('pgp_gpg_public_key', models.TextField(blank=True, null=True, verbose_name='PGP/GPG public key')),
                ('two_factor_auth', models.PositiveSmallIntegerField(choices=[(0, 'Email'), (1, 'Trezor Login'), (2, '2FA Account'), (3, 'None')], default=0, verbose_name='2FA authentication')),
                ('email_confirmation_transaction', models.BooleanField(default=True, verbose_name='email confirmation send/withdrawal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
