# Generated by Django 2.0.2 on 2020-06-18 10:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=255, verbose_name='saved address name')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='address line 2')),
                ('country', django_countries.fields.CountryField(default='US', max_length=2, verbose_name='country')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
                ('postal_code', models.CharField(max_length=255, verbose_name='postal code')),
                ('phone_number', models.CharField(max_length=255, verbose_name='phone_number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.BooleanField(default=False)),
                ('buyer_or_seller', models.PositiveSmallIntegerField(choices=[(0, 'Buyer'), (1, 'Seller')], verbose_name='buyer or seller')),
                ('left_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='left by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_all_feedback', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('id_proof', models.ImageField(upload_to='kyc/')),
                ('selfie', models.ImageField(upload_to='kyc/')),
                ('approved', models.BooleanField(default=False)),
                ('ssn', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYCTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('is_active', models.BooleanField(default=False)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Other/Prefer Not to say')], null=True, verbose_name='gender')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(0, 'Buyer'), (1, 'Seller')], default=0, verbose_name='user type')),
                ('timezone', timezone_field.fields.TimeZoneField(default='UTC', verbose_name='timezone')),
                ('public_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='public name')),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='public email')),
                ('public_url', models.URLField(blank=True, null=True, verbose_name='public URL')),
                ('merchant_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='merchant id')),
                ('date_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='date format')),
                ('time_format', models.CharField(blank=True, max_length=255, null=True, verbose_name='time format')),
                ('use_gravatar', models.BooleanField(default=False, verbose_name='use gravatar')),
                ('pgp_gpg_public_key', models.TextField(blank=True, null=True, verbose_name='PGP/GPG public key')),
                ('two_factor_auth', models.PositiveSmallIntegerField(choices=[(0, 'Email'), (1, 'Trezor Login'), (2, '2FA Account'), (3, 'None')], default=0, verbose_name='2FA authentication')),
                ('email_confirmation_transaction', models.BooleanField(default=True, verbose_name='email confirmation send/withdrawal')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name='is subscribed')),
                ('referance_count', models.IntegerField(default=0, null=True, verbose_name='reference count')),
                ('ipn_secret', models.CharField(blank=True, help_text='This is used to verify that an IPN is from us, use a good random string nobody can guess.', max_length=255, null=True, verbose_name='IPN Secret')),
                ('ipn_url', models.URLField(blank=True, null=True, verbose_name='IPN URL')),
                ('mail_on_new_payment_init', models.BooleanField(default=False, verbose_name='When a user submits a new payment to you')),
                ('mail_on_new_fund_receive', models.BooleanField(default=True, verbose_name='When funds have been received by us for a payment to you.')),
                ('mail_on_fund_sent', models.BooleanField(default=True, verbose_name='When funds for a payment have been sent to you.')),
                ('mail_on_deposit_receive', models.BooleanField(default=True, verbose_name='When a deposit is received on one of your deposit addresses.')),
                ('mail_on_positive_feedback', models.BooleanField(default=True, verbose_name='When positive feedback has been left for you.')),
                ('status_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='status notification email')),
                ('receive_sms', models.BooleanField(default=False, verbose_name='receive SMS text when funds are received')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='SMS phone number')),
                ('refered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=64)),
                ('expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile Activation',
                'verbose_name_plural': 'Profile Activations',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.CharField(max_length=128)),
                ('account_type', models.CharField(choices=[('google_authenticator', 'Google Authenticator/TOTP')], max_length=20)),
                ('key', models.CharField(max_length=128)),
                ('totp', models.CharField(max_length=12, null=True, verbose_name='Authentication Code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_2fa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
