# Generated by Django 2.0.2 on 2018-03-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180322_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='date format'),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='time format'),
        ),
    ]
