# Generated by Django 2.0.2 on 2018-03-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referance_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='referance count'),
        ),
    ]
