# Generated by Django 2.0.2 on 2018-03-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_referance_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referance_count',
            field=models.IntegerField(default=0, null=True, verbose_name='referance count'),
        ),
    ]
