# Generated by Django 2.0.2 on 2018-03-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180327_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referance_count',
        ),
    ]
