# Generated by Django 2.0.2 on 2018-04-03 06:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_referance_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('is_active', models.BooleanField(default=False)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content')),
            ],
        ),
    ]
