# Generated by Django 2.0.2 on 2018-04-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referance_count',
            field=models.IntegerField(default=0, null=True, verbose_name='reference count'),
        ),
    ]
