# Generated by Django 2.0.2 on 2018-04-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180406_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='buyer_or_seller',
            field=models.PositiveSmallIntegerField(verbose_name='buyer or seller'),
        ),
    ]
