# Generated by Django 2.0.2 on 2018-04-12 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0016_auto_20180409_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('account_name', models.CharField(max_length=128)),
                ('account_type', models.CharField(choices=[('google_authenticator', 'Google Authenticator/TOTP')], max_length=20)),
                ('key', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
