# Generated by Django 2.0.2 on 2018-04-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180409_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ipn_secret',
            field=models.CharField(blank=True, help_text='This is used to verify that an IPN is from us, use a good random string nobody can guess.', max_length=255, null=True, verbose_name='IPN Secret'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ipn_url',
            field=models.URLField(blank=True, null=True, verbose_name='IPN URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail_on_deposit_receive',
            field=models.BooleanField(default=True, verbose_name='When a deposit is received on one of your deposit addresses.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail_on_fund_sent',
            field=models.BooleanField(default=True, verbose_name='When funds for a payment have been sent to you.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail_on_new_fund_receive',
            field=models.BooleanField(default=True, verbose_name='When funds have been received by us for a payment to you.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail_on_new_payment_init',
            field=models.BooleanField(default=False, verbose_name='When a user submits a new payment to you'),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail_on_positive_feedback',
            field=models.BooleanField(default=True, verbose_name='When positive feedback has been left for you.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='SMS phone number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='receive_sms',
            field=models.BooleanField(default=False, verbose_name='Receive SMS Text When Funds Are Received'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='status notification email'),
        ),
    ]
