# Generated by Django 2.0.2 on 2018-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180412_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='receive_sms',
            field=models.BooleanField(default=False, verbose_name='receive SMS text when funds are received'),
        ),
    ]
