# Generated by Django 2.0.2 on 2018-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_twofactoraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactoraccount',
            name='totp',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
