# Generated by Django 2.0.2 on 2018-04-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180412_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='merchant id'),
        ),
    ]
