# Generated by Django 2.0.2 on 2018-04-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_twofactoraccount_totp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactoraccount',
            name='totp',
        ),
    ]
