# Generated by Django 2.0.2 on 2018-04-13 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_auto_20180412_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor', models.CharField(blank=True, choices=[('email', 'Email'), ('2fa', 'Linked 2FA Accounts-')], default='email', max_length=20, null=True, verbose_name='2 Factor Authentication')),
                ('email_confirmations', models.CharField(choices=[('required', 'Required'), ('desabled', 'Desabled')], default='required', max_length=20, verbose_name='Email Confirmations for Sends/Withdrawals')),
                ('public_key', models.TextField(max_length=128, verbose_name='PGP/GPG Public Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
