# Generated by Django 2.0.2 on 2018-04-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_twofactorsecurity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactorsecurity',
            name='public_key',
            field=models.TextField(blank=True, max_length=128, verbose_name='PGP/GPG Public Key'),
        ),
    ]
