# Generated by Django 2.0.2 on 2018-04-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20180413_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorsecurity',
            name='user',
        ),
        migrations.DeleteModel(
            name='TwoFactorSecurity',
        ),
    ]
