# Generated by Django 2.0.2 on 2018-04-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180412_1349'),
        ('accounts', '0025_auto_20180413_1130'),
    ]

    operations = [
    ]
