# Generated by Django 2.0.2 on 2018-04-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180413_0955'),
        ('accounts', '0026_merge_20180413_1137'),
    ]

    operations = [
    ]
