# Generated by Django 2.0.2 on 2018-04-27 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_merge_20180419_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofactoraccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_2fa', to=settings.AUTH_USER_MODEL),
        ),
    ]
