# Generated by Django 2.0.2 on 2018-05-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20180427_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='buyer_or_seller',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Buyer'), (1, 'Seller')], verbose_name='buyer or seller'),
        ),
    ]
