# Generated by Django 2.0.2 on 2018-09-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20180924_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='aprroved',
            field=models.BooleanField(default=False),
        ),
    ]
