# Generated by Django 2.0.2 on 2018-09-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_kyc_aprroved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='aprroved',
            new_name='approved',
        ),
    ]
