# Generated by Django 2.0.2 on 2018-10-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20180927_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='documents',
        ),
        migrations.AddField(
            model_name='kyc',
            name='address_line_1',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='address_line_2',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='full_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_number',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_proof',
            field=models.ImageField(default='aaa', upload_to='kyc/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie',
            field=models.ImageField(default='bbb', upload_to='kyc/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserDocuments',
        ),
    ]
