# Generated by Django 2.0.2 on 2018-10-18 05:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0034_kyc_terms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KYC_terms',
            new_name='KYCTerms',
        ),
    ]
