# Generated by Django 2.0.2 on 2018-03-01 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='store name')),
                ('store_url', models.URLField(verbose_name='store url')),
                ('crypto_processor', models.CharField(max_length=255, verbose_name='crypto processor')),
                ('store_email', models.EmailField(max_length=254, verbose_name='store email')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='keywords')),
                ('banner_image_url', models.URLField(verbose_name='banner image url')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('image', models.ImageField(upload_to='store/category', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_store_category', to='store.StoreCategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_stores', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
