# Generated by Django 2.0.2 on 2020-06-18 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('has_voted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, verbose_name='store name')),
                ('store_url', models.URLField(verbose_name='store url')),
                ('crypto_processor', models.CharField(max_length=255, verbose_name='crypto processor')),
                ('store_email', models.EmailField(max_length=254, verbose_name='store email')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='keywords')),
                ('banner_image_url', models.URLField(verbose_name='banner image url')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved')),
                ('votes', models.IntegerField(default=0)),
                ('percent', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, verbose_name='slug')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('publish', models.BooleanField(default=True, verbose_name='publish')),
                ('image', models.FileField(help_text='Add svg image of size 2137x2138 ', upload_to='store/category', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='StorePaymentRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=10)),
                ('item_amount', models.CharField(max_length=128)),
                ('unique_id', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email_addr', models.CharField(max_length=128)),
                ('wallet_address', models.CharField(max_length=128)),
                ('selected_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.Coin')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_store_category', to='store.StoreCategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_stores', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='rating',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='store.Store'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
