# Generated by Django 2.0.2 on 2018-04-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecategory',
            name='image',
            field=models.FileField(upload_to='store/category', verbose_name='image'),
        ),
    ]
