# Generated by Django 2.0.2 on 2018-04-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180405_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storecategory',
            name='slug',
            field=models.SlugField(auto_created=True, verbose_name='slug'),
        ),
    ]
