# Generated by Django 2.0.2 on 2018-04-13 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180406_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_user_stores', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
