# Generated by Django 2.0.2 on 2018-08-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0017_auto_20180810_1042'),
        ('store', '0006_auto_20180416_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorePaymentRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.CharField(max_length=128)),
                ('unique_id', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email_addr', models.CharField(max_length=128)),
                ('wallet_address', models.CharField(max_length=128)),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='store')),
                ('selected_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.Coin')),
            ],
        ),
    ]
