# Generated by Django 2.0.2 on 2018-08-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storepaymentrec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storepaymentrec',
            old_name='merchant_id',
            new_name='store',
        ),
    ]
