# Generated by Django 2.0.2 on 2018-08-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20180830_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storepaymentrec',
            name='store',
        ),
        migrations.AddField(
            model_name='storepaymentrec',
            name='store_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
