# Generated by Django 2.0.2 on 2018-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20181219_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
