# Generated by Django 2.0.2 on 2018-12-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_store_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
