# Generated by Django 2.0.2 on 2018-06-29 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('btn_img', models.ImageField(upload_to='button_maker/')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=128, verbose_name='merchant id')),
                ('item_name', models.CharField(max_length=128)),
                ('item_amount', models.CharField(max_length=128)),
                ('item_number', models.CharField(max_length=128)),
                ('item_qty', models.CharField(max_length=128)),
                ('buyer_qty_edit', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(max_length=128)),
                ('tax_amount', models.CharField(max_length=128)),
                ('allow_shipping_cost', models.BooleanField(default=False)),
                ('shipping_cost', models.CharField(max_length=128)),
                ('shipping_cost_add', models.CharField(max_length=128)),
                ('success_url_link', models.CharField(max_length=128)),
                ('cancel_url_link', models.CharField(max_length=128)),
                ('ipn_url_link', models.CharField(max_length=128)),
                ('allow_buyer_note', models.BooleanField(default=False)),
                ('btn_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_tools.ButtonImage')),
            ],
        ),
    ]
