# Generated by Django 2.0.2 on 2018-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0002_cryptopaymentrec'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopaymentrec',
            name='wallet_address',
            field=models.CharField(default='asa1', max_length=128),
            preserve_default=False,
        ),
    ]
