# Generated by Django 2.0.2 on 2018-07-09 13:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0004_auto_20180705_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='MercSidebarSubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic', models.CharField(max_length=64)),
                ('help_answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order_index', models.IntegerField()),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
            ],
        ),
        migrations.CreateModel(
            name='MercSidebarTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merc_side_topic', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='mercsidebarsubtopic',
            name='main_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_tools.MercSidebarTopic'),
        ),
    ]
