# Generated by Django 2.0.2 on 2018-07-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0005_auto_20180709_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=128, verbose_name='merchant id')),
                ('unique_id', models.CharField(max_length=128)),
                ('item_name', models.CharField(max_length=512)),
                ('item_amount', models.CharField(max_length=128)),
                ('item_number', models.CharField(max_length=128)),
                ('item_qty', models.CharField(max_length=128)),
                ('invoice_number', models.CharField(max_length=128)),
                ('tax_amount', models.CharField(max_length=128)),
                ('shipping_cost', models.CharField(max_length=128)),
                ('ipn_url_link', models.CharField(max_length=128)),
            ],
        ),
    ]
