# Generated by Django 2.0.2 on 2018-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0006_urlmaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmaker',
            name='URL_link',
            field=models.CharField(default='www.dab.com', max_length=256),
            preserve_default=False,
        ),
    ]
