# Generated by Django 2.0.2 on 2018-07-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coin_coin_hosting_type'),
        ('merchant_tools', '0009_auto_20180710_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSQRMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=128, verbose_name='merchant id')),
                ('unique_id', models.CharField(max_length=128, unique=True)),
                ('item_desc', models.CharField(max_length=512)),
                ('item_amount', models.CharField(max_length=128)),
                ('invoice_number', models.CharField(max_length=128)),
                ('custom_field', models.CharField(max_length=128)),
                ('URL_link', models.CharField(max_length=256)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.Coin')),
            ],
        ),
    ]
