# Generated by Django 2.0.2 on 2018-07-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_auto_20180718_1131'),
        ('merchant_tools', '0010_posqrmaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.CharField(max_length=512)),
                ('eq_usd', models.CharField(blank=True, max_length=512, null=True)),
                ('paid_unique_id', models.CharField(blank=True, max_length=512, null=True)),
                ('transaction_id', models.CharField(max_length=64)),
                ('paid_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coins.Coin')),
            ],
        ),
    ]
