# Generated by Django 2.0.2 on 2018-07-20 10:24

import apps.merchant_tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0011_multipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posqrmaker',
            name='time_limit',
            field=models.DateTimeField(default=apps.merchant_tools.models.POSQRMaker.four_hour_hence),
        ),
    ]
