# Generated by Django 2.0.2 on 2018-07-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0012_posqrmaker_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posqrmaker',
            name='time_limit',
            field=models.CharField(max_length=128),
        ),
    ]
