# Generated by Django 2.0.2 on 2018-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0013_auto_20180723_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipayment',
            name='payment_address',
            field=models.CharField(default='1', max_length=512),
            preserve_default=False,
        ),
    ]
