# Generated by Django 2.0.2 on 2018-07-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0015_auto_20180725_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipayment',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
