# Generated by Django 2.0.2 on 2018-07-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0016_auto_20180725_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posqrmaker',
            name='custom_field',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='posqrmaker',
            name='item_desc',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
