# Generated by Django 2.0.2 on 2018-07-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0017_auto_20180726_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmaker',
            name='cancel_url_link',
            field=models.URLField(max_length=128),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='ipn_url_link',
            field=models.URLField(max_length=128),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='item_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='item_qty',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='shipping_cost_add',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='success_url_link',
            field=models.URLField(max_length=128),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
