# Generated by Django 2.0.2 on 2018-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0018_auto_20180730_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmaker',
            name='cancel_url_link',
            field=models.URLField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='ipn_url_link',
            field=models.URLField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='success_url_link',
            field=models.URLField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='urlmaker',
            name='ipn_url_link',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
