# Generated by Django 2.0.2 on 2018-07-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0019_auto_20180731_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmaker',
            name='item_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='urlmaker',
            name='item_qty',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='urlmaker',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='urlmaker',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
