# Generated by Django 2.0.2 on 2018-07-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0020_auto_20180731_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmaker',
            name='cancel_url_link',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='ipn_url_link',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='success_url_link',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cryptopaymentrec',
            name='buyer_note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='posqrmaker',
            name='custom_field',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='posqrmaker',
            name='item_desc',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='urlmaker',
            name='ipn_url_link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
