# Generated by Django 2.0.2 on 2018-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0021_auto_20180731_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipayment',
            name='attempted_usd',
            field=models.CharField(default=0, max_length=512),
        ),
    ]
