# Generated by Django 2.0.2 on 2018-09-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0022_multipayment_attempted_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonmaker',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='shipping_cost_add',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='buttonmaker',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='urlmaker',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='urlmaker',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
