# Generated by Django 2.0.2 on 2018-10-01 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0024_auto_20180928_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationButtonMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=128, verbose_name='merchant id')),
                ('donation_name', models.CharField(max_length=128)),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_number', models.CharField(max_length=128)),
                ('allow_donator_to_adjust_amount', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(max_length=128)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('collect_shipping_address', models.BooleanField(default=False)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('success_url_link', models.URLField(blank=True, max_length=128, null=True)),
                ('cancel_url_link', models.URLField(blank=True, max_length=128, null=True)),
                ('ipn_url_link', models.URLField(blank=True, max_length=128, null=True)),
                ('allow_donator_to_leave_you_a_note', models.BooleanField(default=False)),
                ('btn_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_tools.ButtonImage')),
            ],
        ),
    ]
