# Generated by Django 2.0.2 on 2018-10-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0025_donationbuttonmaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationbuttonmaker',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
