# Generated by Django 2.0.2 on 2018-10-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0026_auto_20181001_0656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationbuttonmaker',
            old_name='allow_donator_to_leave_you_a_note',
            new_name='allow_donor_note',
        ),
    ]
