# Generated by Django 2.0.2 on 2018-10-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0027_auto_20181001_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopaymentrec',
            name='item_name',
            field=models.CharField(default=False, max_length=128),
        ),
    ]
