# Generated by Django 2.0.2 on 2018-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0028_auto_20181003_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptopaymentrec',
            name='item_name',
            field=models.CharField(max_length=128),
        ),
    ]
