# Generated by Django 2.0.2 on 2018-10-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0031_transaction_date'),
        ('merchant_tools', '0029_auto_20181003_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipayment',
            name='paid_in_erc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coins.EthereumToken'),
        ),
        migrations.AlterField(
            model_name='multipayment',
            name='paid_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='coins.Coin'),
        ),
    ]
