# Generated by Django 2.0.2 on 2018-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0032_auto_20181010_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationButtonInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=128, verbose_name='merchant id')),
                ('invoice_number', models.CharField(max_length=128)),
                ('unique_id', models.CharField(max_length=128, unique=True)),
                ('item_name', models.CharField(max_length=128)),
                ('item_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_number', models.CharField(max_length=128)),
                ('item_qty', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('buyer_note', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('email_addr', models.CharField(max_length=128, null=True)),
                ('addr_l1', models.CharField(max_length=128, null=True)),
                ('addr_l2', models.CharField(max_length=128, null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('city', models.CharField(max_length=128, null=True)),
                ('state', models.CharField(max_length=128, null=True)),
                ('zipcode', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=128, null=True)),
                ('URL_link', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
