# Generated by Django 2.0.2 on 2018-10-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0033_donationbuttoninvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationbuttoninvoice',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
