# Generated by Django 2.0.2 on 2018-10-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0036_buttonitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttonitem',
            old_name='unique_id',
            new_name='item_unique_id',
        ),
        migrations.AddField(
            model_name='buttonitem',
            name='item_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
