# Generated by Django 2.0.2 on 2018-10-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0037_auto_20181022_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonitem',
            name='merchant_id',
            field=models.CharField(max_length=128, null=True, verbose_name='merchant id'),
        ),
    ]
