# Generated by Django 2.0.2 on 2018-10-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0038_buttonitem_merchant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonitem',
            name='item_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
