# Generated by Django 2.0.2 on 2018-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0041_simplebuttonmaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleButtonItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_unique_id', models.CharField(max_length=128, unique=True)),
                ('item_name', models.CharField(max_length=128)),
                ('item_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('item_discount', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('merchant_id', models.CharField(max_length=128, null=True, verbose_name='merchant id')),
                ('item_tax', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
            ],
        ),
    ]
