# Generated by Django 2.0.2 on 2018-12-18 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0043_simplebuttoninvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipayment',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
