# Generated by Django 2.0.2 on 2018-12-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0043_simplebuttoninvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipayment',
            name='paid_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
