# Generated by Django 2.0.2 on 2018-12-26 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0044_auto_20181221_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipayment',
            name='paid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
