# Generated by Django 2.0.2 on 2018-12-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0044_auto_20181218_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipayment',
            name='paid_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
