# Generated by Django 2.0.2 on 2018-12-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0044_auto_20181219_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipayment',
            name='paid_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
