# Generated by Django 2.0.2 on 2018-12-18 06:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0045_auto_20181218_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipayment',
            name='paid_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 12, 18, 6, 52, 11, 374354, tzinfo=utc)),
        ),
    ]
