# Generated by Django 2.0.2 on 2018-12-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0045_auto_20181219_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipayment',
            name='merchant_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='merchant id'),
        ),
        migrations.AlterField(
            model_name='multipayment',
            name='paid_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coins.Coin'),
        ),
        migrations.AlterField(
            model_name='multipayment',
            name='paid_in_erc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coins.EthereumToken'),
        ),
    ]
