# Generated by Django 2.0.2 on 2018-12-19 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0046_auto_20181218_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipayment',
            name='paid_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
