# Generated by Django 2.0.2 on 2018-12-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0047_auto_20181219_0827'),
        ('merchant_tools', '0046_auto_20181220_0952'),
    ]

    operations = [
    ]
