# Generated by Django 2.0.2 on 2018-12-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0048_merge_20181221_0957'),
        ('merchant_tools', '0045_multipayment_paid_time'),
    ]

    operations = [
    ]
