# Generated by Django 2.0.2 on 2018-12-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0049_merge_20181226_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipayment',
            name='paid_time',
        ),
    ]
