# Generated by Django 2.0.2 on 2018-12-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0049_merchantpayments'),
        ('merchant_tools', '0050_remove_multipayment_paid_time'),
    ]

    operations = [
    ]
