# Generated by Django 2.0.2 on 2018-12-27 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchant_tools', '0051_merge_20181227_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPaymentWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('private', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='merchantpayments',
            name='merchant',
        ),
        migrations.DeleteModel(
            name='MerchantPayments',
        ),
    ]
