# Generated by Django 2.0.2 on 2019-01-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0052_auto_20181227_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipayment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
