# Generated by Django 2.0.2 on 2019-01-21 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0052_auto_20181227_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentwallet',
            name='initiated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantpaymentwallet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchantpaymentwallet',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
