# Generated by Django 2.0.2 on 2019-01-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0053_auto_20190121_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentwallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
