# Generated by Django 2.0.2 on 2019-01-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0054_merchantpaymentwallet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentwallet',
            name='unique_id',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
