# Generated by Django 2.0.2 on 2019-01-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0055_merchantpaymentwallet_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpaymentwallet',
            name='unique_id',
            field=models.CharField(max_length=128),
        ),
    ]
