# Generated by Django 2.0.2 on 2019-01-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0055_merchantpaymentwallet_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentwallet',
            name='market_rate',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
