# Generated by Django 2.0.2 on 2019-01-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0056_auto_20190122_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpaymentwallet',
            name='market_rate',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
