# Generated by Django 2.0.2 on 2019-01-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0057_merchantpaymentwallet_market_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplebuttoninvoice',
            name='payment_status',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
