# Generated by Django 2.0.2 on 2019-01-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0059_auto_20190123_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantpaymentwallet',
            name='market_rate',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='simplebuttoninvoice',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=256),
        ),
    ]
