# Generated by Django 2.0.2 on 2019-02-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0060_auto_20190123_1240'),
    ]

    operations = [
    ]
