# Generated by Django 2.0.2 on 2019-02-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0060_auto_20190123_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipayment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
