# Generated by Django 2.0.2 on 2019-03-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_tools', '0061_merge_20190201_0547'),
        ('merchant_tools', '0061_multipayment_completed'),
    ]

    operations = [
    ]
