# Generated by Django 2.0.2 on 2018-03-01 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=255, verbose_name='coin name')),
                ('code', models.CharField(max_length=25, verbose_name='code')),
                ('confirms', models.PositiveSmallIntegerField(verbose_name='confirms')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Crypto'), (1, 'Ripple'), (2, 'Ether tokens'), (3, 'Fiat')], default=0, verbose_name='type')),
            ],
            options={
                'verbose_name_plural': 'Coins',
                'verbose_name': 'Coin',
            },
        ),
        migrations.CreateModel(
            name='CoinSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('payment_address', models.CharField(max_length=64, verbose_name='payment address')),
                ('payment_mode', models.PositiveSmallIntegerField(choices=[(0, 'To Balance'), (1, 'ASAP'), (2, 'Nightly'), (3, 'To Balance + Convert'), (4, 'ASAP + Convert')], default=0, verbose_name='payment mode')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='discount field')),
                ('maximum_per_transaction', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='maximum per transaction')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_coin_settings', to='coins.Coin', verbose_name='coin')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Currency', verbose_name='currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_coin_settings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='CoinVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(verbose_name='vote count')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_coin_votes', to='coins.Coin', verbose_name='coin')),
            ],
            options={
                'verbose_name_plural': 'Coin Votes',
                'verbose_name': 'Coin Vote',
            },
        ),
    ]
