# Generated by Django 2.0.2 on 2018-06-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin_type',
            name='coin_hosting',
            field=models.CharField(choices=[('RED', 'red'), ('WHITE', 'white'), ('BLUE', 'blue')], default='RED', max_length=20),
        ),
    ]
