# Generated by Django 2.0.2 on 2018-04-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20180413_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='to_btc',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=10),
        ),
    ]
