# Generated by Django 2.0.2 on 2018-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20180625_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='coin_hosting_type',
        ),
        migrations.AddField(
            model_name='coin',
            name='coin_hosting',
            field=models.CharField(choices=[('RED', 'red'), ('WHITE', 'white'), ('BLUE', 'blue')], default='RED', max_length=20),
        ),
        migrations.DeleteModel(
            name='Coin_Type',
        ),
    ]
