# Generated by Django 2.0.2 on 2018-07-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20180709_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_hosting_type',
            field=models.CharField(choices=[('HOSTED', 'HOSTED'), ('POLONEIX', 'poloneix'), ('BINANCE', 'binance'), ('OKEX', 'okex')], default='HOSTED', max_length=20),
        ),
    ]
