# Generated by Django 2.0.2 on 2018-07-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20180709_1031'),
    ]

    operations = [
    ]
