# Generated by Django 2.0.2 on 2018-07-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coin_coin_hosting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.NewCoin', verbose_name='Coin name')),
            ],
        ),
        migrations.CreateModel(
            name='CoPromotionURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='copromotion url')),
            ],
        ),
        migrations.AddField(
            model_name='copromotion',
            name='urls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.CoPromotionURL', verbose_name='CoPromotion URL'),
        ),
    ]
