# Generated by Django 2.0.2 on 2018-06-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_auto_20180625_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='coin_hosting',
        ),
        migrations.AddField(
            model_name='coin',
            name='coin_hosting_type',
            field=models.CharField(choices=[('HOSTED', 'HOSTED'), ('POLONEIX', 'poloneix'), ('BINANCE', 'binance'), ('OKEX', 'okex')], default='RED', max_length=20),
        ),
    ]
