# Generated by Django 2.0.2 on 2018-04-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coin_to_btc'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_url',
            field=models.URLField(blank=True, null=True, verbose_name='coin site URL'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='to_btc',
            field=models.DecimalField(decimal_places=8, default=1.0, max_digits=10, verbose_name='to BTC value'),
        ),
    ]
