# Generated by Django 2.0.2 on 2018-07-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_auto_20180718_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copromotion',
            name='urls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.CoPromotionURL', verbose_name='CoPromotion URL'),
        ),
    ]
