# Generated by Django 2.0.2 on 2018-04-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_coinconvertrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='max_deposit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coin',
            name='min_deposit',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coin',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='code'),
        ),
    ]
