# Generated by Django 2.0.2 on 2018-04-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_coinconvertrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='code'),
        ),
    ]
