# Generated by Django 2.0.2 on 2018-07-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_auto_20180718_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copromotion',
            name='urls',
        ),
        migrations.AddField(
            model_name='copromotion',
            name='urls',
            field=models.ManyToManyField(null=True, to='coins.CoPromotionURL', verbose_name='CoPromotion URL'),
        ),
    ]
