# Generated by Django 2.0.2 on 2018-04-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_auto_20180419_0606'),
        ('coins', '0006_auto_20180419_0659'),
    ]

    operations = [
    ]
