# Generated by Django 2.0.2 on 2018-07-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coin_coin_hosting_type'),
        ('coins', '0006_auto_20180628_0646'),
    ]

    operations = [
    ]
