# Generated by Django 2.0.2 on 2018-07-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_merge_20180710_1234'),
        ('coins', '0007_auto_20180718_1131'),
    ]

    operations = [
    ]
