# Generated by Django 2.0.2 on 2018-05-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0008_auto_20180424_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=500, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('coin_website', models.CharField(blank=True, default='', max_length=500, verbose_name='coin website')),
                ('coin_url', models.URLField(blank=True, null=True, verbose_name='coin url')),
            ],
        ),
    ]
