# Generated by Django 2.0.2 on 2018-05-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0009_coinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinvote',
            name='coin',
        ),
        migrations.AddField(
            model_name='coin',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='vote count'),
        ),
        migrations.DeleteModel(
            name='CoinVote',
        ),
    ]
