# Generated by Django 2.0.2 on 2018-08-03 09:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0010_coin_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=30)),
                ('contract_address', models.CharField(max_length=20)),
                ('contract_abi', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
