# Generated by Django 2.0.2 on 2018-08-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0011_ethereumtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereumtoken',
            name='contract_address',
            field=models.CharField(max_length=100),
        ),
    ]
