# Generated by Django 2.0.2 on 2018-08-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0011_auto_20180806_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcoin',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coins.Phases', verbose_name='voting_phase'),
            preserve_default=False,
        ),
    ]
