# Generated by Django 2.0.2 on 2018-06-07 11:52

import apps.coins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0011_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='system_tx_id',
            field=models.CharField(default=apps.coins.models.get_random, max_length=50),
        ),
    ]
