# Generated by Django 2.0.2 on 2018-08-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0012_auto_20180803_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethereumtoken',
            old_name='contract_name',
            new_name='contract_symbol',
        ),
    ]
