# Generated by Django 2.0.2 on 2018-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0012_transaction_system_tx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='activaion_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
