# Generated by Django 2.0.2 on 2018-06-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0013_auto_20180608_0646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='activaion_code',
            new_name='activation_code',
        ),
    ]
