# Generated by Django 2.0.2 on 2018-06-12 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0014_auto_20180608_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vite', models.IntegerField(default=0, verbose_name='vote count')),
                ('type', models.CharField(choices=[('follow', 'follow'), ('share', 'share'), ('token', 'token')], default='', max_length=20)),
                ('source', models.CharField(choices=[('facebook', 'facebook'), ('twitter', 'twitter'), ('linkedin', 'linkedin'), ('telegram', 'telegram'), ('reddit', 'reddit'), ('youtube', 'youtube'), ('medium', 'medium'), ('steemit', 'steemit')], default='', max_length=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.Coin', verbose_name='coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
