# Generated by Django 2.0.2 on 2018-08-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_ethereumtokenwallet'),
        ('coins', '0012_newcoin_phase'),
    ]

    operations = [
    ]
