# Generated by Django 2.0.2 on 2018-08-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0015_merge_20180809_1323'),
    ]

    operations = [
    ]
