# Generated by Django 2.0.2 on 2018-06-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0015_coinvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinvote',
            name='vite',
        ),
    ]
