# Generated by Django 2.0.2 on 2018-08-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0013_auto_20180810_0911'),
        ('coins', '0015_merge_20180809_1323'),
    ]

    operations = [
    ]
