# Generated by Django 2.0.2 on 2018-08-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_merge_20180810_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumtoken',
            name='coin_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='coin name'),
        ),
        migrations.AddField(
            model_name='ethereumtoken',
            name='display',
            field=models.BooleanField(default=False, help_text='Show/Hide this coin anytime'),
        ),
        migrations.AddField(
            model_name='ethereumtoken',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a 35X35 image for better experience', upload_to='', verbose_name='image'),
        ),
    ]
