# Generated by Django 2.0.2 on 2018-06-15 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_remove_coinvote_vite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_sent_address', models.CharField(max_length=250)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.Transaction')),
            ],
        ),
    ]
