# Generated by Django 2.0.2 on 2018-08-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_merge_20180810_0928'),
        ('coins', '0017_auto_20180810_1042'),
    ]

    operations = [
    ]
