# Generated by Django 2.0.2 on 2018-06-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0017_claimrefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinvote',
            name='source',
            field=models.CharField(choices=[('facebook', 'facebook'), ('twitter', 'twitter'), ('linkedin', 'linkedin'), ('telegram', 'telegram'), ('reddit', 'reddit'), ('youtube', 'youtube'), ('medium', 'medium'), ('steemit', 'steemit'), ('instagram', 'instagram')], default='', max_length=20),
        ),
    ]
