# Generated by Django 2.0.2 on 2018-06-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0018_auto_20180615_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinvote',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='vote count'),
        ),
    ]
