# Generated by Django 2.0.2 on 2018-08-31 05:48

import apps.coins.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0018_merge_20180820_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200)),
                ('input_coin', models.CharField(blank=True, max_length=20)),
                ('output_coin', models.CharField(blank=True, max_length=20)),
                ('txn_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('address_from', models.CharField(blank=True, max_length=200)),
                ('address_to', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('system_tx_id', models.CharField(default=apps.coins.models.get_random, max_length=50)),
                ('activation_code', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
