# Generated by Django 2.0.2 on 2018-08-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0019_converttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='converttransaction',
            name='receive_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
