# Generated by Django 2.0.2 on 2018-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0019_coinvote_vote_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('company_email', models.EmailField(max_length=254, verbose_name='comapny email')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('contact_number', models.CharField(max_length=20, verbose_name='contact number')),
                ('secondary_number', models.CharField(blank=True, max_length=20, null=True)),
                ('token_name', models.CharField(max_length=10, verbose_name='token name')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website URL')),
                ('best_time_to_call', models.DateTimeField()),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='logo_url')),
                ('hash_tags', models.CharField(max_length=100, verbose_name='hash tags')),
                ('twitter_handle', models.CharField(max_length=20, verbose_name='twitter handle')),
                ('fb_page', models.URLField(blank=True, null=True, verbose_name='facebook page')),
                ('twitter_page', models.URLField(blank=True, null=True, verbose_name='twitter page')),
                ('linkedin_page', models.URLField(blank=True, null=True, verbose_name='linkedin page')),
                ('telegram_page', models.URLField(blank=True, null=True, verbose_name='telegram page')),
                ('reddit_page', models.URLField(blank=True, null=True, verbose_name='reddit page')),
            ],
        ),
    ]
