# Generated by Django 2.0.2 on 2018-06-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0020_newcoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcoin',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
