# Generated by Django 2.0.2 on 2018-09-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_merge_20180810_0928'),
        ('coins', '0020_converttransaction_receive_address'),
    ]

    operations = [
    ]
