# Generated by Django 2.0.2 on 2018-09-04 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0018_merge_20180810_1247'),
        ('coins', '0020_converttransaction_receive_address'),
    ]

    operations = [
    ]
