# Generated by Django 2.0.2 on 2018-09-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0021_merge_20180905_0544'),
        ('coins', '0021_merge_20180906_1256'),
    ]

    operations = [
    ]
