# Generated by Django 2.0.2 on 2018-09-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0021_merge_20180906_1256'),
        ('coins', '0021_merge_20180904_0710'),
    ]

    operations = [
    ]
