# Generated by Django 2.0.2 on 2018-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0021_newcoin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcoin',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='vote count'),
        ),
    ]
