# Generated by Django 2.0.2 on 2018-09-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0022_merge_20180907_0417'),
        ('coins', '0022_merge_20180906_1326'),
    ]

    operations = [
    ]
