# Generated by Django 2.0.2 on 2018-09-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0023_merge_20180907_0420'),
        ('coins', '0021_merge_20180905_0623'),
    ]

    operations = [
    ]
