# Generated by Django 2.0.2 on 2018-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0023_auto_20180619_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcoin',
            name='token_name',
        ),
        migrations.AddField(
            model_name='newcoin',
            name='code',
            field=models.CharField(default='fsdf', max_length=10, unique=True, verbose_name='coin code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newcoin',
            name='name',
            field=models.CharField(default='sdfds', max_length=30, unique=True, verbose_name='coin name'),
            preserve_default=False,
        ),
    ]
