# Generated by Django 2.0.2 on 2018-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0024_auto_20180619_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinvote',
            name='vote_count',
        ),
        migrations.RemoveField(
            model_name='newcoin',
            name='best_time_to_call',
        ),
        migrations.AlterField(
            model_name='newcoin',
            name='vote_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='vote count'),
        ),
    ]
