# Generated by Django 2.0.2 on 2018-09-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0025_moneropaymentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneropaymentid',
            name='user',
        ),
        migrations.DeleteModel(
            name='MoneroPaymentid',
        ),
    ]
