# Generated by Django 2.0.2 on 2018-09-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0026_auto_20180919_1251'),
        ('coins', '0027_moneropaymentid'),
    ]

    operations = [
    ]
