# Generated by Django 2.0.2 on 2018-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0028_merge_20180921_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypaltransaction',
            name='system_tx_status',
            field=models.BooleanField(default=False),
        ),
    ]
