# Generated by Django 2.0.2 on 2018-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0029_paypaltransaction_system_tx_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumtoken',
            name='payment_transaction_allowed',
            field=models.BooleanField(default=False, help_text='Show/Hide on payment gateway'),
        ),
        migrations.AddField(
            model_name='ethereumtoken',
            name='swap_allowed',
            field=models.BooleanField(default=False, help_text='Show/Hide on coin convert page'),
        ),
    ]
