# Generated by Django 2.0.2 on 2018-11-02 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0031_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
