# Generated by Django 2.0.2 on 2018-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0032_paybyname_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayByNamePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
