# Generated by Django 2.0.2 on 2018-11-08 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coins', '0033_paybynamepackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayByNamePurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_status', models.BooleanField(default=False)),
                ('tx_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.PayByNamePackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
