# Generated by Django 2.0.2 on 2018-11-15 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0034_paybynamepurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 11, 55, 25, 431280)),
        ),
    ]
