# Generated by Django 2.0.2 on 2018-11-19 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0039_auto_20181119_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybyname',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.PayByNamePurchase', verbose_name='purchase history'),
        ),
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 19, 11, 20, 25, 993553, tzinfo=utc)),
        ),
    ]
