# Generated by Django 2.0.2 on 2018-11-20 11:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0040_auto_20181119_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 11, 24, 6, 794439, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paybyname',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coins.PayByNamePurchase', verbose_name='purchase history'),
        ),
    ]
