# Generated by Django 2.0.2 on 2018-11-21 06:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0041_auto_20181120_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 6, 34, 23, 490848, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paybyname',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='coins.PayByNamePurchase', verbose_name='purchase history'),
        ),
    ]
