# Generated by Django 2.0.2 on 2018-11-21 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0042_auto_20181121_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paybyname',
            name='purchase',
        ),
        migrations.AddField(
            model_name='paybynamepurchase',
            name='paybyname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paybyname', to='coins.PaybyName', verbose_name='paybyname usage'),
        ),
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 9, 16, 31, 739522, tzinfo=utc)),
        ),
    ]
