# Generated by Django 2.0.2 on 2018-12-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0045_auto_20181130_1012'),
        ('coins', '0044_auto_20181130_0806'),
    ]

    operations = [
    ]
