# Generated by Django 2.0.2 on 2018-12-03 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0047_auto_20181203_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 9, 14, 53, 397938, tzinfo=utc)),
        ),
    ]
