# Generated by Django 2.0.2 on 2018-12-05 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0048_auto_20181203_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 6, 58, 41, 378865, tzinfo=utc)),
        ),
    ]
