# Generated by Django 2.0.2 on 2018-12-18 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0048_auto_20181218_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 6, 45, 1, 993496, tzinfo=utc)),
        ),
    ]
