# Generated by Django 2.0.2 on 2018-12-19 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0049_auto_20181219_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 12, 28, 0, 604603, tzinfo=utc)),
        ),
    ]
