# Generated by Django 2.0.2 on 2018-12-05 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0049_auto_20181205_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 9, 0, 46, 72264, tzinfo=utc)),
        ),
    ]
