# Generated by Django 2.0.2 on 2018-12-05 12:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0050_auto_20181205_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 12, 12, 36, 803368, tzinfo=utc)),
        ),
    ]
