# Generated by Django 2.0.2 on 2018-12-19 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0050_auto_20181219_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 13, 32, 3, 551488, tzinfo=utc)),
        ),
    ]
