# Generated by Django 2.0.2 on 2018-12-05 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0051_auto_20181205_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 5, 12, 27, 9, 50842, tzinfo=utc)),
        ),
    ]
