# Generated by Django 2.0.2 on 2018-12-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0051_auto_20181219_1332'),
        ('coins', '0052_auto_20181219_0827'),
    ]

    operations = [
    ]
