# Generated by Django 2.0.2 on 2018-12-06 04:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0052_auto_20181205_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 6, 4, 58, 36, 804770, tzinfo=utc)),
        ),
    ]
