# Generated by Django 2.0.2 on 2018-12-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0053_merge_20181220_1233'),
        ('coins', '0053_merge_20181220_1253'),
    ]

    operations = [
    ]
