# Generated by Django 2.0.2 on 2018-12-21 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0053_merge_20181220_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 21, 10, 30, 59, 526882, tzinfo=utc)),
        ),
    ]
