# Generated by Django 2.0.2 on 2018-12-26 05:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0054_auto_20181221_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 5, 18, 59, 249366, tzinfo=utc)),
        ),
    ]
