# Generated by Django 2.0.2 on 2018-12-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0046_merge_20181207_0904'),
        ('coins', '0054_auto_20181207_1149'),
    ]

    operations = [
    ]
