# Generated by Django 2.0.2 on 2018-12-27 05:27

import apps.coins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0054_auto_20181221_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=apps.coins.models.update_expiry),
        ),
    ]
