# Generated by Django 2.0.2 on 2018-12-11 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0055_merge_20181210_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 4, 34, 28, 583324, tzinfo=utc)),
        ),
    ]
