# Generated by Django 2.0.2 on 2018-12-26 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0056_auto_20181226_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 5, 37, 17, 929482, tzinfo=utc)),
        ),
    ]
