# Generated by Django 2.0.2 on 2018-12-12 06:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0056_auto_20181211_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 6, 0, 43, 184451, tzinfo=utc)),
        ),
    ]
