# Generated by Django 2.0.2 on 2018-12-13 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0057_auto_20181212_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 5, 35, 3, 125640, tzinfo=utc)),
        ),
    ]
