# Generated by Django 2.0.2 on 2018-12-14 03:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0058_auto_20181213_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 14, 3, 38, 19, 428770, tzinfo=utc)),
        ),
    ]
