# Generated by Django 2.0.2 on 2018-12-26 08:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0058_auto_20181226_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 26, 8, 59, 39, 749723, tzinfo=utc)),
        ),
    ]
