# Generated by Django 2.0.2 on 2018-12-17 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0059_auto_20181214_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 4, 17, 57, 934028, tzinfo=utc)),
        ),
    ]
