# Generated by Django 2.0.2 on 2018-12-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0059_auto_20181226_0859'),
        ('coins', '0054_merge_20181220_1303'),
    ]

    operations = [
    ]
