# Generated by Django 2.0.2 on 2018-12-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0055_auto_20181227_0527'),
        ('coins', '0060_merge_20181226_1117'),
    ]

    operations = [
    ]
