# Generated by Django 2.0.2 on 2018-12-17 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0060_auto_20181217_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 8, 46, 4, 864549, tzinfo=utc)),
        ),
    ]
