# Generated by Django 2.0.2 on 2019-01-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0060_merge_20181227_0737'),
        ('coins', '0060_merge_20181227_0627'),
    ]

    operations = [
    ]
