# Generated by Django 2.0.2 on 2019-01-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0061_merge_20190102_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaddress',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='label',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
