# Generated by Django 2.0.2 on 2019-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0063_merge_20190104_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneropaymentid',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
