# Generated by Django 2.0.2 on 2018-12-19 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0036_auto_20181115_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 6, 42, 40, 783437, tzinfo=utc)),
        ),
    ]
