# Generated by Django 2.0.2 on 2018-12-19 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0064_auto_20181219_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 6, 43, 43, 300161, tzinfo=utc)),
        ),
    ]
