# Generated by Django 2.0.2 on 2019-02-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0064_moneropaymentid_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinsetting',
            name='erc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_coin_settings', to='coins.EthereumToken', verbose_name='erc'),
        ),
        migrations.AlterField(
            model_name='coinsetting',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_coin_settings', to='coins.Coin', verbose_name='coin'),
        ),
        migrations.AlterField(
            model_name='coinsetting',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='discount field'),
        ),
        migrations.AlterField(
            model_name='coinsetting',
            name='maximum_per_transaction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='maximum per transaction'),
        ),
        migrations.AlterField(
            model_name='coinsetting',
            name='payment_address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='payment address'),
        ),
        migrations.AlterField(
            model_name='coinsetting',
            name='payment_mode',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'To Balance'), (1, 'ASAP'), (2, 'Nightly'), (3, 'To Balance + Convert'), (4, 'ASAP + Convert')], default=0, null=True, verbose_name='payment mode'),
        ),
    ]
