# Generated by Django 2.0.2 on 2018-12-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0052_auto_20181219_0827'),
        ('coins', '0065_auto_20181219_0643'),
    ]

    operations = [
    ]
