# Generated by Django 2.0.2 on 2018-12-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0051_auto_20181219_1332'),
        ('coins', '0067_auto_20181220_0952'),
    ]

    operations = [
    ]
