# Generated by Django 2.0.2 on 2018-12-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0048_auto_20181130_1003'),
        ('coins', '0063_auto_20181219_0539'),
        ('coins', '0045_auto_20181129_0714'),
        ('coins', '0068_merge_20181220_1321'),
        ('coins', '0053_merge_20181220_1253'),
    ]

    operations = [
    ]
