# Generated by Django 2.0.2 on 2018-12-27 05:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0071_auto_20181226_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybyname',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 5, 6, 11, 238046, tzinfo=utc)),
        ),
    ]
