# Generated by Django 2.0.2 on 2018-12-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0072_auto_20181227_0506'),
        ('coins', '0059_auto_20181226_0859'),
    ]

    operations = [
    ]
