# Generated by Django 2.0.2 on 2018-12-27 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0073_merge_20181227_0519'),
        ('coins', '0055_auto_20181227_0527'),
    ]

    operations = [
    ]
