# Generated by Django 2.0.2 on 2019-01-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0062_auto_20190103_0646'),
        ('coins', '0074_merge_20181227_0815'),
    ]

    operations = [
    ]
