# Generated by Django 2.0.2 on 2019-01-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0075_merge_20190104_0448'),
        ('coins', '0063_merge_20190104_0445'),
    ]

    operations = [
    ]
