# Generated by Django 2.0.2 on 2019-01-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0064_moneropaymentid_address'),
        ('coins', '0076_merge_20190104_0452'),
    ]

    operations = [
    ]
