# Generated by Django 2.0.2 on 2019-03-06 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0077_merge_20190114_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaddress',
            name='current_balance',
            field=models.CharField(blank=True, default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='last_check',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
