# Generated by Django 2.0.2 on 2019-03-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0078_auto_20190306_0608'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCommision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_commission_type', models.CharField(choices=[('FLAT', 'FLAT'), ('PERCENTAGE', 'PERCENTAGE')], default='HOSTED', max_length=20)),
                ('commission_percentage', models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='commission percentage')),
                ('commission_flat_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='commission flat rate')),
            ],
        ),
    ]
