# Generated by Django 2.0.2 on 2019-03-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0079_tradecommision'),
        ('coins', '0065_auto_20190219_0549'),
    ]

    operations = [
    ]
