# Generated by Django 2.0.2 on 2019-03-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0080_merge_20190319_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='phases',
            name='extra_message',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
