# Generated by Django 2.0.2 on 2019-03-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0081_phases_extra_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='token_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.EthereumToken'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.Coin'),
        ),
    ]
