# Generated by Django 2.0.2 on 2019-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0084_ethereumtoken_extra_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='extra_message',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
