# Generated by Django 2.0.2 on 2019-04-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0086_auto_20190403_1103'),
        ('coins', '0086_auto_20190401_0851'),
    ]

    operations = [
    ]
