# Generated by Django 2.0.2 on 2019-04-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0087_merge_20190404_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_api', models.CharField(choices=[('coingecko', 'coingecko'), ('coincap', 'coincap')], default='coincap', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='tradecommision',
            name='transaction_commission_type',
            field=models.CharField(choices=[('FLAT', 'FLAT'), ('PERCENTAGE', 'PERCENTAGE')], default='FLAT', max_length=20),
        ),
    ]
