# Generated by Django 2.0.2 on 2019-05-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0088_auto_20190418_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='min_transaction_fees',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=10),
        ),
    ]
