# Generated by Django 2.0.2 on 2019-05-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0089_coin_min_transaction_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='min_transaction_fees',
            field=models.FloatField(default=0),
        ),
    ]
