# Generated by Django 2.0.2 on 2019-07-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0090_auto_20190527_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybynamepurchase',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
