# Generated by Django 2.0.2 on 2020-06-18 10:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('visit', models.CharField(max_length=128)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_question', models.CharField(max_length=512)),
                ('api_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=64)),
                ('requester_email', models.EmailField(max_length=254)),
                ('coin_symbol', models.CharField(max_length=10)),
                ('coin_name', models.CharField(max_length=64)),
                ('coin_url', models.CharField(max_length=128)),
                ('coin_algorithm', models.CharField(max_length=255)),
                ('coin_source_url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=30, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(max_length=512)),
                ('faq_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HelpSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_topic', models.CharField(max_length=64)),
                ('help_answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order_index', models.IntegerField()),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
            ],
        ),
        migrations.CreateModel(
            name='InformationalSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform_topic', models.CharField(max_length=64)),
                ('inform_answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order_index', models.IntegerField()),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
            ],
        ),
        migrations.CreateModel(
            name='LegalSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_topic', models.CharField(max_length=64)),
                ('help_answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order_index', models.IntegerField()),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
            ],
        ),
        migrations.CreateModel(
            name='PluginDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_cart_logo', models.ImageField(upload_to='', verbose_name='image')),
                ('last_update', models.DateField(auto_now_add=True)),
                ('download_url', models.URLField(verbose_name='link')),
                ('auth_type', models.CharField(max_length=10)),
                ('zero_confirm', models.BooleanField()),
                ('video_url', models.URLField(verbose_name='Video URL')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_topic', models.CharField(max_length=64)),
                ('receive_answer', ckeditor_uploader.fields.RichTextUploadingField()),
                ('order_index', models.IntegerField()),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255, verbose_name='provider')),
                ('link', models.URLField(verbose_name='link')),
                ('publish', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=128, unique=True)),
                ('topic', models.CharField(max_length=128)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
            ],
        ),
        migrations.CreateModel(
            name='UITheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=128)),
                ('file_name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
