# Generated by Django 2.0.2 on 2018-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
