# Generated by Django 2.0.2 on 2018-05-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_sociallink_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=64)),
                ('requester_email', models.EmailField(max_length=254)),
                ('coin_symbol', models.CharField(max_length=10)),
                ('coin_name', models.CharField(max_length=64)),
                ('coin_url', models.CharField(max_length=128)),
                ('coin_algorithm', models.CharField(max_length=255)),
                ('coin_source_url', models.CharField(max_length=128)),
            ],
        ),
    ]
