# Generated by Django 2.0.2 on 2018-05-14 11:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_coinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(max_length=512)),
                ('faq_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HelpSidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_topic', models.CharField(max_length=64)),
                ('help_answer', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
