# Generated by Django 2.0.2 on 2018-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_faq_helpsidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsidebar',
            name='order_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
