# Generated by Django 2.0.2 on 2018-05-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_helpsidebar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpsidebar',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
