# Generated by Django 2.0.2 on 2018-05-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20180514_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpsidebar',
            name='help_answer',
        ),
    ]
