# Generated by Django 2.0.2 on 2018-05-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_legalsidebar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legalsidebar',
            old_name='legal_answer',
            new_name='help_answer',
        ),
        migrations.RenameField(
            model_name='legalsidebar',
            old_name='legal_topic',
            new_name='help_topic',
        ),
    ]
