# Generated by Django 2.0.2 on 2018-06-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20180514_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_cart_logo', models.ImageField(upload_to='', verbose_name='image')),
                ('last_update', models.DateField(auto_now_add=True)),
                ('download_url', models.URLField(verbose_name='link')),
                ('auth_type', models.CharField(max_length=10)),
                ('zero_confirm', models.BooleanField()),
                ('video_url', models.URLField(verbose_name='Video URL')),
            ],
        ),
    ]
