# Generated by Django 2.0.2 on 2018-07-11 09:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_plugindownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=128)),
                ('topic', models.CharField(max_length=128)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield')),
            ],
        ),
    ]
