# Generated by Django 2.0.2 on 2018-07-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_staticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='page_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
