# Generated by Django 2.0.2 on 2019-04-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_uitheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitheme',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
